# Site settings
title: Indico Project
email: indico-team@cern.ch
description: > # this means to ignore newlines until "baseurl:"
 Indico Project Official site - Indico is a powerful event (meetings, conferences, lectures)
 management system developed at CERN
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getindico.io" # the base hostname & protocol for your site
twitter_username: getindico
github_username: indico
disqus_shortname: indico-project

plugins:
  - jekyll-feed
  - jemoji
  - premonition

# Build settings
markdown: kramdown

premonition:
  types:
    contribution:
      template: |
        <div class="premonition {% if meta.style %}{{meta.style}} {% endif %}{{type}}">
          <i class="fas {% if attrs contains 'fa-icon' and attrs.fa-icon != "" %}{{ attrs.fa-icon }}{% else %}{{ "fa-star" }}{% endif %}"></i>
          <div class="content">
            {% if header %}<p class="header">{{title}}</p>{% endif %}{{content}}
          </div>
        </div>
      default_title: "Community Contribution"
